[project]
name="src"
version="0.0.1"
description = "Vehcle Insurance MLOps"
authors=[{name="Saksham Bansal", email="bansalrohini29@gmail.com"}]

[tool.setuptools]
packages = {find={}}

[tool.setuptools.dynamic]
dependencies = {file="requirements.txt"}
